framgia/sph-sun-overflow

- README.md
- backend/.dockerignore
- backend/Dockerfile
- docker-compose.yml
- frontend/Dockerfile
- frontend/next.config.js
https://framgiaph.backlog.com/view/SUN_OVERFLOW-155
`cd backend`
`cp .env.example .env`
`cd ..`
`docker-compose up`
Docker Desktop
Docker for FE and BE are now working and accepting changes
None
None
> [Overflow-155] - [BUG-FIX] Setup Docker

- README.md
- backend/Dockerfile
- docker-compose.yml
https://framgiaph.backlog.com/view/SUN_OVERFLOW-155
docker-compose up
None
Docker for BE can now install new packages
None
None
> [Overflow-155] - [BUG-FIX] Docker BE installing package

- backend/app/Models/User.php
- backend/composer.json
- backend/composer.lock
- backend/database/seeders/DatabaseSeeder.php
- backend/graphql/schema.graphql
- backend/graphql/user/mutation.graphql
- backend/graphql/user/query.graphql
- backend/graphql/user/type.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-161
None
None
GraphQL set-up in the backend including the sample query, mutation and types for users
The sample user folder contains code that is basing the default user field in laravel, please update once the correct user field are migrated
NA
> [Overflow-161] Setup GraphQL

- backend/app/Models/Role.php
- backend/database/migrations/2023_01_19_070828_create_roles_table.php
- backend/database/seeders/DatabaseSeeder.php
- backend/database/seeders/RoleSeeder.php
https://framgiaph.backlog.com/view/SUN_OVERFLOW-164
```
cd backend
```
* Should setup environment variables for the Database
* None
> [Overflow-164] - Create migration and seeder files for Roles [BE]

- frontend/components/atoms/Button/index.tsx
- frontend/components/molecules/RichTextEditor/index.tsx
- frontend/components/organisms/AnswerComponent/index.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/postcss.config.js
https://framgiaph.backlog.com/view/SUN_OVERFLOW-25
cd frontend
npm i
none
Answer Component with  RichText Editor and a button for submitting an answer
non
> [Overflow-25] Answer Component

- backend/app/Models/Permission.php
- backend/database/migrations/2023_01_20_050611_create_permissions_table.php
- backend/database/seeders/DatabaseSeeder.php
- backend/database/seeders/PermissionSeeder.php
https://framgiaph.backlog.com/view/SUN_OVERFLOW-165
```
cd backend
```
* Should setup environment variables for the Database
* None
> [Overflow-165] Create migration and seeder files for Permission [BE]

- frontend/pages/index.tsx
- frontend/tailwind.config.js
https://framgiaph.backlog.com/view/SUN_OVERFLOW-174
None
None
Custom color theme in tailwind.
None
None
> [Overflow-174] Set-up color theme

- backend/app/Models/Answer.php
- backend/app/Models/User.php
- backend/database/factories/AnswerFactory.php
- backend/database/migrations/2023_01_23_102844_create_answers_table.php
- backend/database/seeders/AnswerSeeder.php
- backend/database/seeders/DatabaseSeeder.php
https://framgiaph.backlog.com/view/SUN_OVERFLOW-168
cd backend
Tables roles, users and questions should already have data rows.
Answers table is now populated with data. It is also ensured that the author (user) of the answer should not be the same with the author of its respective question.
none
> [Overflow-168] Model, Migration and Seeder Files for Answers

- frontend/components/molecules/NotificationDropdown/index.tsx
- frontend/components/molecules/SearchBar/index.tsx
- frontend/components/molecules/UserDropdown/index.tsx
- frontend/components/organisms/Navbar/index.tsx
- frontend/package-lock.json
https://framgiaph.backlog.com/view/SUN_OVERFLOW-5
cd frontend
npm run dev
none
Updated navbar spacing
none
> [Overflow-5] - [BUGFIX] Update navbar markup

- backend/graphql/answer/mutation.graphql
- backend/graphql/answer/query.graphql
- backend/graphql/answer/type.graphql
- backend/graphql/schema.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-26
cd backend
None
Can create an answer in `http://localhost:8000/graphiql`
> [Overflow-26] Create API adding answers

- backend/app/Models/Answer.php
- backend/app/Models/Comment.php
- backend/app/Models/Question.php
- backend/database/factories/CommentFactory.php
- backend/database/migrations/2023_01_24_064358_create_comments_table.php
- backend/database/seeders/CommentSeeder.php
- backend/database/seeders/DatabaseSeeder.php
https://framgiaph.backlog.com/view/SUN_OVERFLOW-169
cd backend
Questions and answers table should have data rows.
Comments table now has data.
none
> [Overflow-169] Model, Migration and Seeder Files for Comments

- backend/graphql/answer/mutation.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-28
cd backend
none
Can only update the **content** of an existing answer in http://localhost:8000/graphiql
none
1
2
3
> [Overflow-28] Create API for updating answers

- backend/app/Models/Answer.php
- backend/app/Models/Question.php
- backend/app/Models/Vote.php
- backend/database/factories/VoteFactory.php
- backend/database/migrations/2023_01_25_033431_create_votes_table.php
- backend/database/seeders/DatabaseSeeder.php
- backend/database/seeders/VoteSeeder.php
https://framgiaph.backlog.com/view/SUN_OVERFLOW-171
cd backend
Questions and answers table should have data rows.
Votes table now has data
none
> [Overflow-171] Model, Migration and Seeder Files for Votes

- backend/graphql/role/query.graphql
- backend/graphql/role/type.graphql
- backend/graphql/schema.graphql
- backend/graphql/user/query.graphql
- backend/graphql/user/type.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-10
```
cd backend
```
- Should setup environment variables for the Database
- I also updated the User type
> [Overflow-10] API Get Permissions of User

- backend/app/Models/Tag.php
- backend/app/Models/User.php
- backend/database/migrations/2023_01_25_031917_create_tags_table.php
- backend/database/migrations/2023_01_25_033418_user_tag.php
- backend/database/migrations/2023_01_26_055630_tag_user.php
- backend/database/seeders/DatabaseSeeder.php
- backend/database/seeders/TagSeeder.php
https://framgiaph.backlog.com/view/SUN_OVERFLOW-175
```
cd backend
```
* Should setup environment variables for the Database
- I also included the pivot table for users and tags
> [Overflow-175] Create migration and seeder files for Tags

- backend/app/Models/Tag.php
- backend/app/Models/User.php
- backend/graphql/schema.graphql
- backend/graphql/tag/query.graphql
- backend/graphql/tag/type.graphql
- backend/graphql/user/type.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-11
```
cd backend
```
* Should setup environment variables for the Database
- None
> [Overflow-11] Get API for watched tags

- backend/app/Models/Answer.php
- backend/app/Models/Comment.php
- backend/app/Models/User.php
- backend/app/Models/UserNotification.php
- backend/app/Observers/AnswerObserver.php
- backend/app/Observers/CommentObserver.php
- backend/app/Observers/VoteObserver.php
- backend/app/Providers/EventServiceProvider.php
- backend/database/migrations/2023_01_26_021728_create_user_notifications_table.php
- backend/database/seeders/AnswerSeeder.php
- backend/database/seeders/CommentSeeder.php
- backend/database/seeders/VoteSeeder.php
- backend/graphql/answer/mutation.graphql
- backend/graphql/comment/query.graphql
- backend/graphql/comment/type.graphql
- backend/graphql/notification/query.graphql
- backend/graphql/notification/type.graphql
- backend/graphql/question/type.graphql
- backend/graphql/schema.graphql
- backend/graphql/user/type.graphql
- backend/graphql/vote/query.graphql
- backend/graphql/vote/type.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-6
cd backend
none
Notifications are generated from the following:
- Answer creation (Posted an answer)
- Answer update (Accepted an answer)
- Comment creation (Posted a comment on an answer/question)
- Vote creation (Voted on an answer/question)
Will still update functionality to accommodate follows and teams notifications when these features are already available.
> [Overflow-6] Notification API

- backend/graphql/schema.graphql
- backend/graphql/team/query.graphql
- backend/graphql/team/type.graphql
- backend/graphql/user/type.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-12
```
cd backend
```
- Should setup environment variables for the Database
> [Overflow-12] Get api for my teams

- backend/composer.lock
- backend/graphql/answer/type.graphql
- backend/graphql/question/query.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-21
None
None
Get question and its comments with answers and its comments
None
> [Overflow-21] Create API for retrieving Question, Answers, and Comments

- backend/app/GraphQL/Queries/Questions.php
- backend/config/lighthouse.php
- backend/graphql/question/query.graphql
- backend/graphql/question/type.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-186
cd backend
none
A paginated list of all questions will be displayed. 
Questions can also be filtered by created date and whether they are answered or unanswered.
none
**Unfiltered query:**
**Filtered query:**
> [Overflow-186] Retrieve Question List API

- backend/app/GraphQL/Mutations/CreateAnswer.php
- backend/graphql/answer/mutation.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-26
None
None
Create mutations for answer
None
> [Overflow-26] - [Bugfix] - Create Api for adding answers

- backend/graphql/question/mutation.graphql
- frontend/components/atoms/Icons/index.tsx
- frontend/components/molecules/Avatar/index.tsx
- frontend/components/molecules/Bookmark/index.tsx
- frontend/components/molecules/Pill/index.tsx
- frontend/components/molecules/Tags/index.tsx
- frontend/components/molecules/UserDropdown/index.tsx
- frontend/components/molecules/Votes/index.tsx
- frontend/components/organisms/Navbar/index.tsx
- frontend/components/organisms/QuestionDetail/index.tsx
- frontend/components/organisms/Sidebar/index.tsx
- frontend/components/templates/layouts/index.tsx
- frontend/package-lock.json
- frontend/pages/questions/[id].tsx
https://framgiaph.backlog.com/view/SUN_OVERFLOW-20
None
None
Question detail page with only the question component is present 
Updated the layouts and fix the navbar dropdown pop-up
None
> [Overflow-20] Implement Question Component

- frontend/.prettierrc
https://framgiaph.backlog.com/view/SUN_OVERFLOW-219
- After this is merged, a lot of changes will be done once you format your code
> [Overflow-219] Add .prettierrc config file

- backend/app/Exceptions/CustomException.php
- backend/app/GraphQL/Mutations/CreateQuestion.php
- backend/app/Models/Question.php
- backend/app/Models/Tag.php
- backend/database/migrations/2023_02_02_095142_add_team_id_to_questions_table.php
- backend/database/migrations/2023_02_03_014656_create_question_tag_table.php
- backend/database/migrations/2023_02_03_014919_create_question_tag_table.php
- backend/graphql/question/mutation.graphql
- backend/graphql/question/type.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-37
None
Authorization required in graphql playground
Api for posting question
None
> [Overflow-37] Create API for Posting Question

- backend/app/GraphQL/Mutations/CreateComment.php
- backend/app/GraphQL/Mutations/UpdateComment.php
- backend/graphql/comment/mutation.graphql
- backend/graphql/question/query.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-27
cd backend
none
A user can create and update comments
- Included some updates for Question List query to include @ guard directive
> [Overflow-27] Create and Update Comments

- backend/app/GraphQL/Mutations/CreateQuestion.php
- backend/graphql/question/mutation.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-222
None
Authenticated user in graphql playground
Remove duplicated migration file 
None
None
> [Overflow-37] [Bugfix] Create API for Posting Question

- backend/app/Models/Question.php
- backend/database/seeders/VoteSeeder.php
- backend/graphql/question/type.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-223
None
Authenticated User in graphql playground
Added vote_count
None
None
> [Overflow-223] Bugfix Create API for retrieving Question only

- backend/graphql/tag/query.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-220
will add a query that pull all the tags with names similar to the one provided
> [Overflow-220] Get API for Tag Suggestions

- backend/app/GraphQL/Mutations/AddWatchedTag.php
- backend/app/GraphQL/Mutations/RemoveWatchedTag.php
- backend/graphql/user/mutation.graphql
https://framgiaph.backlog.com/view/SUN_OVERFLOW-221
uses Auth::user() to get user_id
> [Overflow-221] Add/Remove Api for WatchedTags
